---
- name: restart blackbox exporter
  become: true
  systemd:
    daemon_reload: true
    name: blackbox_exporter
    state: restarted
  tags:
    - molecule-notest

- name: reload blackbox exporter
  become: true
  systemd:
    name: blackbox_exporter
    state: reloaded
  tags:
    - molecule-notest
