---
- hosts: all
  tasks:
    - name: install sudo | CentOS
      dnf:
        name: sudo
        state: present
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: install sudo | Debian
      apt:
        name: sudo
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'